// Generate "sprites" -  single file which contains
// many icons inside, Goal - reduce images download
// time for client's browsers
// Steps:
// 1. Take all individual  files
// 2. Run gulp-svg-sprite plugin to pack them into
//   one SVG XML file.

var gulp = require('gulp'),
    svgSprite = require('gulp-svg-sprite'),
    rename = require('gulp-rename'),
    del = require('del'),
    svg2png = require('gulp-svg2png');

// Configuration object for the plugin
// Generates CSS file with positions and offsets
// for every icon.
//
var config = {
  shape: {  // To add some padding between the icons in the sprite
            // Otherwize tiny part of neighboring icons may be visible
            // in case of tought packed sprite file
      spacing: {
        padding: 1
      }      
  },
  mode: {
    css: {
      variables: {  // custom var to replace .svg file extention with .png
        replaceSvgWithPng: function() {
           return function(sprite, render) {
             return render( sprite ).split('.svg').join('.png');           }
        }
      },
      sprite: 'sprite.svg',
      render: {
        css: {
          template: './gulp/templates/sprite.css'
        }
      }
    }
  }
}

// Begin Clean of temp folders from previous run
// Goal: to avoid growing number of old sprite-xxxx.svg files in folder.
//       guarantee clean environment for new sprite file generation
gulp.task('beginClean', function() {
  return del(['./app/temp/sprite', './app/assets/images/sprites']);
});

// Generate new sprite file according to config object ,
//    and template file
gulp.task('createSprite',['beginClean'], function() {
  return gulp.src('./app/assets/images/icons/**/*.svg')
    .pipe(svgSprite(config))
    .pipe(gulp.dest('./app/temp/sprite'));
});

// Create PNG copy of SVG sprite for outdated browsers
gulp.task('createPngCopy', ['createSprite'], function() {
    return gulp.src('./app/temp/sprite/css/*.svg')
        .pipe(svg2png())
        .pipe(gulp.dest('./app/temp/sprite/css'));
});

// Copy .svg, AND .png files with icons, generated by createSprite
gulp.task('copySpriteGraphic',['createPngCopy'], function() {
    return gulp.src('./app/temp/sprite/css/**/*.{svg,png}')
          .pipe(gulp.dest('./app/assets/images/sprites'));
});

// Copy created Sprite CSS file into centralized location
gulp.task('copySpriteCSS',['createSprite'], function() {
  return gulp.src('./app/temp/sprite/css/*.css')
    .pipe(rename('_sprite.css'))
    .pipe(gulp.dest('./app/assets/styles/modules'));
});

// End Clean  to remove tmp directory: ./app/temp/sprite
gulp.task('endClean',['copySpriteGraphic','copySpriteCSS'], function() {
  return del('./app/temp/sprite');
});

// Run Icon Sprite generation and distribution to directory tree
gulp.task('icons', ['beginClean','createSprite','createPngCopy',
                    'copySpriteGraphic','copySpriteCSS','endClean']);
